# Uncomment the next line to define a global platform for your project
# platform :ios, '6.0'

target 'i-Report' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for i-Report
  pod 'AFNetworking', '~> 3.0'
  pod 'SDWebImage'
  pod 'Masonry'
  pod 'MJRefresh'
  pod 'MJExtension'
  
end
